import Config

reload_enabled = System.get_env("POKER_DISABLE_RELOAD") != "1"

watchers =
  if reload_enabled do
    [
      node: [
        "node_modules/webpack/bin/webpack.js",
        "--mode",
        "development",
        "--watch-stdin",
        cd: Path.expand("../assets", __DIR__),
        env: [{"NODE_OPTIONS", "--openssl-legacy-provider"}]
      ]
    ]
  else
    []
  end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :poker, PokerWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: 4005],
  debug_errors: true,
  code_reloader: reload_enabled,
  check_origin: false,
  server: true,
  watchers: watchers

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

if reload_enabled do
  # Watch static and templates for browser reloading.
  config :poker, PokerWeb.Endpoint,
    live_reload: [
      patterns: [
        ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
        ~r"priv/gettext/.*(po)$",
        ~r"lib/poker_web/(live|views)/.*(ex)$",
        ~r"lib/poker_web/templates/.*(eex)$"
      ]
    ]
end

# Do not include metadata nor timestamps in development logs
config :logger,
  level: :info

config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
